version: '3'
services:
  postgres:
    container_name: "postgres-bookings"
    hostname: postgres
    image: postgres:11.17-alpine
    networks:
      - bookings
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookings
      POSTGRES_HOST_AUTH_METHOD: trust
  mailhog:
    container_name: "mailhog-bookings"
    image: mailhog/mailhog
    networks:
      - bookings
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  bookings:
    name: "bookings"
    driver: bridge